[build]
base = "client"
publish = "client/build"
command = "GENERATE_SOURCEMAP=false npm run build"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
DISABLE_ESLINT_PLUGIN = "true"
CI = "false"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
